// Catalogue de serveurs MCP hébergés, vérifiés : découverte OAuth + inscription dynamique du client (connexion en un clic).
export const CATALOGUE = [
  { id: 'zapier', nom: 'Zapier', url: 'https://mcp.zapier.com/api/mcp/mcp', categorie: 'Passerelle', description: "Passerelle Zapier vers les comptes de l'utilisateur : Gmail (lire, répondre, envoyer), Google Agenda, Google Drive, Notion, Airtable, Granola, Typeform et des milliers d'autres applications." },
  { id: 'notion', nom: 'Notion', url: 'https://mcp.notion.com/mcp', categorie: 'Notes et docs', description: 'Notion : rechercher, lire, créer et modifier des pages et bases de données.' },
  { id: 'airtable', nom: 'Airtable', url: 'https://mcp.airtable.com', categorie: 'Données', description: 'Airtable : bases, tables et enregistrements (lecture, création, mise à jour).' },
  { id: 'granola', nom: 'Granola', url: 'https://mcp.granola.ai/mcp', categorie: 'Réunions', description: 'Granola : notes et transcriptions de réunions, recherche dans les comptes rendus.' },
  { id: 'fireflies', nom: 'Fireflies', url: 'https://api.fireflies.ai/mcp', categorie: 'Réunions', description: 'Fireflies : transcriptions et résumés de réunions.' },
  { id: 'make', nom: 'Make', url: 'https://mcp.make.com/mcp', categorie: 'Automatisation', description: 'Make : lancer et gérer des scénarios d\'automatisation.' },
  { id: 'canva', nom: 'Canva', url: 'https://mcp.canva.com/mcp', categorie: 'Design', description: 'Canva : rechercher, créer et exporter des designs.' },
  { id: 'miro', nom: 'Miro', url: 'https://mcp.miro.com/', categorie: 'Design', description: 'Miro : tableaux blancs, lire et créer du contenu.' },
  { id: 'figma', nom: 'Figma', url: 'https://mcp.figma.com/mcp', categorie: 'Design', description: 'Figma : fichiers et composants de design.' },
  { id: 'linear', nom: 'Linear', url: 'https://mcp.linear.app/mcp', categorie: 'Projets', description: 'Linear : tickets, projets et cycles.' },
  { id: 'atlassian', nom: 'Jira & Confluence', url: 'https://mcp.atlassian.com/v1/mcp', categorie: 'Projets', description: 'Atlassian : tickets Jira et pages Confluence.' },
  { id: 'asana', nom: 'Asana', url: 'https://mcp.asana.com/sse', categorie: 'Projets', description: 'Asana : tâches et projets.' },
  { id: 'monday', nom: 'monday.com', url: 'https://mcp.monday.com/mcp', categorie: 'Projets', description: 'monday.com : tableaux, éléments et mises à jour.' },
  { id: 'clickup', nom: 'ClickUp', url: 'https://mcp.clickup.com/mcp', categorie: 'Projets', description: 'ClickUp : tâches, listes et documents.' },
  { id: 'todoist', nom: 'Todoist', url: 'https://ai.todoist.net/mcp', categorie: 'Tâches', description: 'Todoist : tâches et projets personnels.' },
  { id: 'calendly', nom: 'Calendly', url: 'https://mcp.calendly.com/', categorie: 'Agenda', description: 'Calendly : disponibilités, liens de réservation et rendez-vous pris.' },
  { id: 'dropbox', nom: 'Dropbox', url: 'https://mcp.dropbox.com/mcp', categorie: 'Fichiers', description: 'Dropbox : rechercher et lire des fichiers.' },
  { id: 'intercom', nom: 'Intercom', url: 'https://mcp.intercom.com/mcp', categorie: 'Clients', description: 'Intercom : conversations et contacts clients.' },
  { id: 'stripe', nom: 'Stripe', url: 'https://mcp.stripe.com', categorie: 'Finance', description: 'Stripe : clients, paiements, factures et abonnements.' },
  { id: 'paypal', nom: 'PayPal', url: 'https://mcp.paypal.com/mcp', categorie: 'Finance', description: 'PayPal : transactions, factures et paiements.' },
  { id: 'vercel', nom: 'Vercel', url: 'https://mcp.vercel.com', categorie: 'Développement', description: 'Vercel : projets, déploiements et journaux.' },
  { id: 'supabase', nom: 'Supabase', url: 'https://mcp.supabase.com/mcp', categorie: 'Développement', description: 'Supabase : projets, bases de données et fonctions.' },
  { id: 'cloudflare', nom: 'Cloudflare', url: 'https://bindings.mcp.cloudflare.com/mcp', categorie: 'Développement', description: 'Cloudflare : Workers, KV, R2, D1.' },
  { id: 'netlify', nom: 'Netlify', url: 'https://netlify-mcp.netlify.app/mcp', categorie: 'Développement', description: 'Netlify : sites et déploiements.' },
  { id: 'sentry', nom: 'Sentry', url: 'https://mcp.sentry.dev/mcp', categorie: 'Développement', description: 'Sentry : erreurs et incidents applicatifs.' },
  { id: 'huggingface', nom: 'Hugging Face', url: 'https://huggingface.co/mcp', categorie: 'IA', description: 'Hugging Face : modèles, jeux de données et espaces.' },
  { id: 'webflow', nom: 'Webflow', url: 'https://mcp.webflow.com/sse', categorie: 'Web', description: 'Webflow : sites et contenus CMS.' },
  { id: 'cloudinary', nom: 'Cloudinary', url: 'https://asset-management.mcp.cloudinary.com/mcp', categorie: 'Médias', description: 'Cloudinary : images et vidéos hébergées.' },
  { id: 'square', nom: 'Square', url: 'https://mcp.squareup.com/sse', categorie: 'Finance', description: 'Square : ventes, catalogue et clients.' },
];
export const parId = (id) => CATALOGUE.find((e) => e.id === id) || null;
